project:
  type: website

format:
  html:
    embed-resources: true
    code-fold: true
    code-tools: false
    code-block-bg: false
    code-block-border-left: false
    echo: false # Hide code by default
    fig-width: 7
    fig-height: 5

metadata:
  title: "Unlocking Potential: A Global Journey Through Literacy"
  subtitle: "Trends, Disparities, and Data Insights"
  author: "Amal Anil Kumar"
  date: "2024-04-26"
  lang: en